version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  proxy-server:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "3002:3002"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    depends_on:
      - app
    restart: unless-stopped 